### PR TITLE
CITY-20: Add post "Co-design Session#2: Dynamic Streets"

### PR DESCRIPTION
**Pull request by simonbates**
https://issues.fluidproject.org/browse/CITY-20

### CODE REVIEW

**Comment by simonbates** [comment]
That's a really good question @michelled. I think we probably should. Do you have ideas on a good way to mark that up?

**Comment by simonbates** [comment]
I've prepared a transcript here:

https://gist.github.com/simonbates/f9afabc732813cfcd9d53d7247b4d97e

**Comment by simonbates** [comment]
This is going to be a lot of text to add to the post page itself. Maybe we put the transcripts on their own web pages and link?

**Comment by simonbates** [comment]
https://www.w3.org/WAI/tutorials/images/complex/

**Comment by simonbates** [comment]
Here's what I'm thinking:

- make a new template type for Image Descriptions
- make separate pages for each of the 2 whiteboard image descriptions
- link to the description pages from the post page

Reasonable?

**Comment by michelled** [comment]
Yes, that sounds good. Thanks Simon

**Comment by sepidehshahi** [comment]
Hi Simon and Michelle,
I agree with you that there is lot of information in those images, we have the same problem in the first post with our wish board and black board. I think the best way to approach this is that a description of all that information will be provided in a follow-up post where we describe the results from these sessions. So we can either remove those images or just generally describe them and refer to an upcoming article with more details.

Thanks,

SEPIDEH SHAHI

SENIOR INCLUSIVE DESIGNER
INCLUSIVE DESIGN RESEARCH CENTRE, OCAD UNIVERSITY

T: 416 977 6000 x3958
E: sshahi@ocadu.ca<mailto:sshahi@ocadu.ca>

www.ocadu.ca<http://www.ocadu.ca/>
www.idrc.ocad.ca<http://www.idrc.ocad.ca/>

On Aug 30, 2018, at 1:46 PM, Simon Bates <notifications@github.com<mailto:notifications@github.com>> wrote:


Here's what I'm thinking:

  *   make a new template type for Image Descriptions
  *   make separate pages for each of the 2 whiteboard image descriptions
  *   link to the description pages from the post page

Reasonable?

**Comment by simonbates** [comment]
@michelled I've added description pages for the whiteboard images. Please take a look.

**Pull request merged**
